### PR TITLE
Fixed Bug about the msg lenght more than 512 can't output right HmacSHA1

### PR DESCRIPTION
**Pull request by JacketPants**
I run the program in Windows and use GCC 4.9.2

### CODE REVIEW

**Comment by vyuh** [comment]
Currently, this program cannot find the length of message itself. Are you sure that you set the correct message length [here](https://github.com/JacketPants/hmac-sha1/blob/a2f918e01b77b3e47ab816397b228c6d84f5d260/hmac-sha1-test.c#L8) manually, when you tested? Can you give an example that shows the bug?

**Comment by JacketPants** [comment]
This is a example. The msg is longer than 512 bits.

msg="n7wSuuCKF6KF4bseRq3hI3UGR7jTkdcbmhDsTMP1GF6axcH5vjay3IFvhPv5ImSuWok2DpMILZjlQ8DcQmP0izu2jfosO3np"
key="8Xk1LnmFnXq1qIGQTToZNOX1U6HMNyCJ"
HmacSHA1="35d84090e86a3614119c6c83e04abe6d0c39303b"

I use this code to test.
```
#include "hmac-sha1.c"
#include <string.h>
int main (int argc, char **argv) {
  b32 hash[5];
  char *msg = "n7wSuuCKF6KF4bseRq3hI3UGR7jTkdcbmhDsTMP1GF6axcH5vjay3IFvhPv5ImSuWok2DpMILZjlQ8DcQmP0izu2jfosO3np";
  char *key = "8Xk1LnmFnXq1qIGQTToZNOX1U6HMNyCJ";
  bitstr m,k;

  m.d = msg;
  m.l[0] = strlen(msg)*8;
  m.l[1] = m.l[0]/512;
  
  k.d = key;
  k.l[0] = strlen(key)*8;
  k.l[1] = k.l[0]/512;

  hmac_sha1 (&k, &m, hash);
  rpr (hash);
  return 0;
}
```

If I use your test code when it longer than 512 bits the HmacSHA1 is wrong.
The HmacSHA1 that example in your test code is "0c6f521756d79d1b690461efed7769b87811fc0b"

I understand the length is
```
bitstr.l[0] // length of bit
bitstr.l[1] // I guess is bitstr.l[0]/512
```

**Comment by vyuh** [comment]
Thanks. I think I understood the bug. I had to move the pointer forward only by 64 bytes (512 bits) but I added 512 bytes. But, regarding your commit, I think [this line](https://github.com/vyuh/hmac-sha1/pull/1/commits/a2f918e01b77b3e47ab816397b228c6d84f5d260#diff-67800cb0a005ca79089e863b944e5e6eL71) must be kept where it is. Is there a reason you moved it above the `if` statement?

**Comment by vyuh** [comment]
Also `bitstr.l` is just an array to keep the length of message as a simple binary number. This number can have `2*8*sizeof(unsigned)` bits. The lesser significant bits are stored in `bitstr.l[0]`.

**Pull request merged**
